name: Deploy

on:
  workflow_call:
    secrets:
      GOOGLE_CLOUD_KEY:
        required: true
      MEDCASE_GITHUB_TOKEN:
        required: true
    inputs:
      PROJECT_ID:
        required: false
        type: string
      TARGET:
        required: false
        type: string
      STAGE:
        required: false
        type: string

env:
  MEDCASE_GITHUB_TOKEN: ${{ secrets.MEDCASE_GITHUB_TOKEN }}
  STAGE: ${{ inputs.STAGE }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: yarn install
      - run: yarn build:${{ inputs.STAGE }}
        if: "${{ env.STAGE != '' }}"
      - run: yarn build
        if: "${{ env.STAGE == '' }}"
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.MEDCASE_GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.GOOGLE_CLOUD_KEY }}
          channelId: live
          projectId: ${{ inputs.PROJECT_ID }}
          target: ${{ inputs.TARGET }}
