name: Deploy

on:
  workflow_call:
    secrets:
      GOOGLE_CLOUD_KEY:
        required: true
      MEDCASE_GITHUB_TOKEN:
        required: true
    inputs:
      PROJECT_ID:
        required: true
        type: string
      STAGE:
        required: false
        type: string
      USE_NPMRC:
        required: false
        type: string
        default: 'true'
env:
  MEDCASE_GITHUB_TOKEN: ${{ secrets.MEDCASE_GITHUB_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v2
      - run: cp .npmrc .npmrc.temp
        if: "${{ inputs.USE_NPMRC == 'true' }}"
      - uses: danielr1996/envsubst-action@1.0.0
        if: "${{ inputs.USE_NPMRC == 'true' }}"
        with:
          input: .npmrc.temp
          output: .npmrc
      - run: yarn install
        if: "${{ inputs.STAGE != '' }}"
      - run: yarn build:${{ inputs.STAGE }}
        if: "${{ inputs.STAGE != '' }}"
      - run: yarn build
        if: "${{ inputs.STAGE == '' }}"
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: ${{ secrets.GOOGLE_CLOUD_KEY }}
      - id: deploy
        uses: google-github-actions/deploy-appengine@v0
        with:
          project_id: ${{ inputs.PROJECT_ID }}
      - id: url
        run: echo "${{ steps.deploy.outputs.url }}"
